# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrooge < Formula
  desc "Life's expensive - now you see why."
  homepage "https://github.com/yannickkirschen/scrooge"
  version "0.1.0-alpha4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha4/scrooge_Darwin_x86_64.tar.gz"
      sha256 "aba663fc9b7bf02a8a4f84c99c0ac3ae40e9e6b4e68273b65e1468fbc0d13634"

      def install
        bin.install "scrooge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha4/scrooge_Darwin_arm64.tar.gz"
      sha256 "fcc1ad3e12d9654370484ac6ab4c8ccb438551a4e6c2d5d79791e36301c7c372"

      def install
        bin.install "scrooge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha4/scrooge_Linux_x86_64.tar.gz"
      sha256 "28b74cfa5e7c473103f96d7c8fb2f8d76b5b8048ee12d657494ed43ffef2c0e6"
      def install
        bin.install "scrooge"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha4/scrooge_Linux_arm64.tar.gz"
      sha256 "9aa402738ef597c1741a98f4bc4f7d6721975a46a4fe0d2cc55b82ff5e5554a4"
      def install
        bin.install "scrooge"
      end
    end
  end

  test do
    system "#{bin}/scrooge --help"
  end
end
