# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrooge < Formula
  desc "Life's expensive - now you see why."
  homepage "https://github.com/yannickkirschen/scrooge"
  version "0.1.0-alpha3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha3/scrooge_Darwin_x86_64.tar.gz"
      sha256 "eab15d6581111374fca7ec20813edbca9db65f681f42b980f875482e4236c779"

      def install
        bin.install "scrooge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha3/scrooge_Darwin_arm64.tar.gz"
      sha256 "1cc8d76536edac3b65ee321b4ceef162868031ecdb6dc9700f66aeb5539402e9"

      def install
        bin.install "scrooge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha3/scrooge_Linux_x86_64.tar.gz"
      sha256 "73c73cb8b1f95fc4f6f43ebd07e3c4016afe8d8987abbfe5f0c896403d332af3"
      def install
        bin.install "scrooge"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha3/scrooge_Linux_arm64.tar.gz"
      sha256 "bd4b20eb28072138f3032dadee1e773e4a5fc0b6831dac1465c0d4331a04c13f"
      def install
        bin.install "scrooge"
      end
    end
  end

  test do
    system "#{bin}/scrooge --help"
  end
end
