# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrooge < Formula
  desc "Life's expensive - now you see why."
  homepage "https://github.com/yannickkirschen/scrooge"
  version "0.1.0-alpha1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha1/scrooge_Darwin_x86_64.tar.gz"
      sha256 "971796c87baba6a3f1ab5e00cc26f19ab4b7c2090d7483c9d0c42f17173818a1"

      def install
        bin.install "scrooge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha1/scrooge_Darwin_arm64.tar.gz"
      sha256 "4fcabff1ebf44853fe7197bc4a6b83f433631d67ca089a7d53ac78c34f7c851f"

      def install
        bin.install "scrooge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha1/scrooge_Linux_x86_64.tar.gz"
      sha256 "ad3dfb48612963df0a30a2f835bced5a707e8202ace3ac420920e09c3d04c694"
      def install
        bin.install "scrooge"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yannickkirschen/scrooge/releases/download/0.1.0-alpha1/scrooge_Linux_arm64.tar.gz"
      sha256 "b3169210dcdc248e0cd310ad03579c9a97a596a9d45ff2478b9ecfcfc913a93f"
      def install
        bin.install "scrooge"
      end
    end
  end

  test do
    system "#{bin}/scrooge --help"
  end
end
